/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentTownRouteImport } from './routes/agent-town'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DesktopOsRouteImport } from './routes/desktop-os'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as VoiceAiRouteImport } from './routes/voice-ai'
import { Route as OrderRefRouteImport } from './routes/order.$ref'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTownRoute = AgentTownRouteImport.update({
  id: '/agent-town',
  path: '/agent-town',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopOsRoute = DesktopOsRouteImport.update({
  id: '/desktop-os',
  path: '/desktop-os',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceAiRoute = VoiceAiRouteImport.update({
  id: '/voice-ai',
  path: '/voice-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRefRoute = OrderRefRouteImport.update({
  id: '/order/$ref',
  path: '/order/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-town': typeof AgentTownRoute
  '/checkout': typeof CheckoutRoute
  '/desktop-os': typeof DesktopOsRoute
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/voice-ai': typeof VoiceAiRoute
  '/order/$ref': typeof OrderRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-town': typeof AgentTownRoute
  '/checkout': typeof CheckoutRoute
  '/desktop-os': typeof DesktopOsRoute
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/voice-ai': typeof VoiceAiRoute
  '/order/$ref': typeof OrderRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-town': typeof AgentTownRoute
  '/checkout': typeof CheckoutRoute
  '/desktop-os': typeof DesktopOsRoute
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/voice-ai': typeof VoiceAiRoute
  '/order/$ref': typeof OrderRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-town'
    | '/checkout'
    | '/desktop-os'
    | '/docs'
    | '/integrations'
    | '/pricing'
    | '/voice-ai'
    | '/order/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-town'
    | '/checkout'
    | '/desktop-os'
    | '/docs'
    | '/integrations'
    | '/pricing'
    | '/voice-ai'
    | '/order/$ref'
  id:
    | '__root__'
    | '/'
    | '/agent-town'
    | '/checkout'
    | '/desktop-os'
    | '/docs'
    | '/integrations'
    | '/pricing'
    | '/voice-ai'
    | '/order/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentTownRoute: typeof AgentTownRoute
  CheckoutRoute: typeof CheckoutRoute
  DesktopOsRoute: typeof DesktopOsRoute
  DocsRoute: typeof DocsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PricingRoute: typeof PricingRoute
  VoiceAiRoute: typeof VoiceAiRoute
  OrderRefRoute: typeof OrderRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-town': {
      id: '/agent-town'
      path: '/agent-town'
      fullPath: '/agent-town'
      preLoaderRoute: typeof AgentTownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-os': {
      id: '/desktop-os'
      path: '/desktop-os'
      fullPath: '/desktop-os'
      preLoaderRoute: typeof DesktopOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-ai': {
      id: '/voice-ai'
      path: '/voice-ai'
      fullPath: '/voice-ai'
      preLoaderRoute: typeof VoiceAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$ref': {
      id: '/order/$ref'
      path: '/order/$ref'
      fullPath: '/order/$ref'
      preLoaderRoute: typeof OrderRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentTownRoute: AgentTownRoute,
  CheckoutRoute: CheckoutRoute,
  DesktopOsRoute: DesktopOsRoute,
  DocsRoute: DocsRoute,
  IntegrationsRoute: IntegrationsRoute,
  PricingRoute: PricingRoute,
  VoiceAiRoute: VoiceAiRoute,
  OrderRefRoute: OrderRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
