/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DesktopOsRouteImport } from './routes/desktop-os'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as OpenSourceRouteImport } from './routes/open-source'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VoiceAiRouteImport } from './routes/voice-ai'
import { Route as AdminDownloadsRouteImport } from './routes/admin.downloads'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as ModelsSlugRouteImport } from './routes/models.$slug'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as OpenSourceIndexRouteImport } from './routes/open-source.index'
import { Route as OpenSourceAnythingllmRouteImport } from './routes/open-source.anythingllm'
import { Route as OpenSourceAudacityRouteImport } from './routes/open-source.audacity'
import { Route as OpenSourceDeepLiveCamRouteImport } from './routes/open-source.deep-live-cam'
import { Route as OpenSourceFacefusionRouteImport } from './routes/open-source.facefusion'
import { Route as OpenSourceHermesAgentRouteImport } from './routes/open-source.hermes-agent'
import { Route as OpenSourceJanAiRouteImport } from './routes/open-source.jan-ai'
import { Route as OpenSourceKdenliveRouteImport } from './routes/open-source.kdenlive'
import { Route as OpenSourceOpenclawRouteImport } from './routes/open-source.openclaw'
import { Route as OpenSourceOpencutRouteImport } from './routes/open-source.opencut'
import { Route as OpenSourceOpenhandsRouteImport } from './routes/open-source.openhands'
import { Route as OpenSourcePocketbaseRouteImport } from './routes/open-source.pocketbase'
import { Route as OpenSourceSeoSpiderRouteImport } from './routes/open-source.seo-spider'
import { Route as OpenSourceShotcutRouteImport } from './routes/open-source.shotcut'
import { Route as OpenSourceTuttleRouteImport } from './routes/open-source.tuttle'
import { Route as OpenSourceUpscaylRouteImport } from './routes/open-source.upscayl'
import { Route as OrderRefRouteImport } from './routes/order.$ref'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopOsRoute = DesktopOsRouteImport.update({
  id: '/desktop-os',
  path: '/desktop-os',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceRoute = OpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceAiRoute = VoiceAiRouteImport.update({
  id: '/voice-ai',
  path: '/voice-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/admin/downloads',
  path: '/admin/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsSlugRoute = ModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/modules/$slug',
  path: '/modules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceIndexRoute = OpenSourceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceAnythingllmRoute = OpenSourceAnythingllmRouteImport.update({
  id: '/anythingllm',
  path: '/anythingllm',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceAudacityRoute = OpenSourceAudacityRouteImport.update({
  id: '/audacity',
  path: '/audacity',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceDeepLiveCamRoute = OpenSourceDeepLiveCamRouteImport.update({
  id: '/deep-live-cam',
  path: '/deep-live-cam',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceFacefusionRoute = OpenSourceFacefusionRouteImport.update({
  id: '/facefusion',
  path: '/facefusion',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceHermesAgentRoute = OpenSourceHermesAgentRouteImport.update({
  id: '/hermes-agent',
  path: '/hermes-agent',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceJanAiRoute = OpenSourceJanAiRouteImport.update({
  id: '/jan-ai',
  path: '/jan-ai',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceKdenliveRoute = OpenSourceKdenliveRouteImport.update({
  id: '/kdenlive',
  path: '/kdenlive',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceOpenclawRoute = OpenSourceOpenclawRouteImport.update({
  id: '/openclaw',
  path: '/openclaw',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceOpencutRoute = OpenSourceOpencutRouteImport.update({
  id: '/opencut',
  path: '/opencut',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceOpenhandsRoute = OpenSourceOpenhandsRouteImport.update({
  id: '/openhands',
  path: '/openhands',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourcePocketbaseRoute = OpenSourcePocketbaseRouteImport.update({
  id: '/pocketbase',
  path: '/pocketbase',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceSeoSpiderRoute = OpenSourceSeoSpiderRouteImport.update({
  id: '/seo-spider',
  path: '/seo-spider',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceShotcutRoute = OpenSourceShotcutRouteImport.update({
  id: '/shotcut',
  path: '/shotcut',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceTuttleRoute = OpenSourceTuttleRouteImport.update({
  id: '/tuttle',
  path: '/tuttle',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OpenSourceUpscaylRoute = OpenSourceUpscaylRouteImport.update({
  id: '/upscayl',
  path: '/upscayl',
  getParentRoute: () => OpenSourceRoute,
} as any)
const OrderRefRoute = OrderRefRouteImport.update({
  id: '/order/$ref',
  path: '/order/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/desktop-os': typeof DesktopOsRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/integrations': typeof IntegrationsRoute
  '/open-source': typeof OpenSourceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/voice-ai': typeof VoiceAiRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/open-source/anythingllm': typeof OpenSourceAnythingllmRoute
  '/open-source/audacity': typeof OpenSourceAudacityRoute
  '/open-source/deep-live-cam': typeof OpenSourceDeepLiveCamRoute
  '/open-source/facefusion': typeof OpenSourceFacefusionRoute
  '/open-source/hermes-agent': typeof OpenSourceHermesAgentRoute
  '/open-source/jan-ai': typeof OpenSourceJanAiRoute
  '/open-source/kdenlive': typeof OpenSourceKdenliveRoute
  '/open-source/openclaw': typeof OpenSourceOpenclawRoute
  '/open-source/opencut': typeof OpenSourceOpencutRoute
  '/open-source/openhands': typeof OpenSourceOpenhandsRoute
  '/open-source/pocketbase': typeof OpenSourcePocketbaseRoute
  '/open-source/seo-spider': typeof OpenSourceSeoSpiderRoute
  '/open-source/shotcut': typeof OpenSourceShotcutRoute
  '/open-source/tuttle': typeof OpenSourceTuttleRoute
  '/open-source/upscayl': typeof OpenSourceUpscaylRoute
  '/order/$ref': typeof OrderRefRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/open-source/': typeof OpenSourceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/desktop-os': typeof DesktopOsRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/voice-ai': typeof VoiceAiRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/open-source/anythingllm': typeof OpenSourceAnythingllmRoute
  '/open-source/audacity': typeof OpenSourceAudacityRoute
  '/open-source/deep-live-cam': typeof OpenSourceDeepLiveCamRoute
  '/open-source/facefusion': typeof OpenSourceFacefusionRoute
  '/open-source/hermes-agent': typeof OpenSourceHermesAgentRoute
  '/open-source/jan-ai': typeof OpenSourceJanAiRoute
  '/open-source/kdenlive': typeof OpenSourceKdenliveRoute
  '/open-source/openclaw': typeof OpenSourceOpenclawRoute
  '/open-source/opencut': typeof OpenSourceOpencutRoute
  '/open-source/openhands': typeof OpenSourceOpenhandsRoute
  '/open-source/pocketbase': typeof OpenSourcePocketbaseRoute
  '/open-source/seo-spider': typeof OpenSourceSeoSpiderRoute
  '/open-source/shotcut': typeof OpenSourceShotcutRoute
  '/open-source/tuttle': typeof OpenSourceTuttleRoute
  '/open-source/upscayl': typeof OpenSourceUpscaylRoute
  '/order/$ref': typeof OrderRefRoute
  '/blog': typeof BlogIndexRoute
  '/compare': typeof CompareIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/models': typeof ModelsIndexRoute
  '/modules': typeof ModulesIndexRoute
  '/open-source': typeof OpenSourceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/desktop-os': typeof DesktopOsRoute
  '/download': typeof DownloadRoute
  '/faq': typeof FaqRoute
  '/integrations': typeof IntegrationsRoute
  '/open-source': typeof OpenSourceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/voice-ai': typeof VoiceAiRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/open-source/anythingllm': typeof OpenSourceAnythingllmRoute
  '/open-source/audacity': typeof OpenSourceAudacityRoute
  '/open-source/deep-live-cam': typeof OpenSourceDeepLiveCamRoute
  '/open-source/facefusion': typeof OpenSourceFacefusionRoute
  '/open-source/hermes-agent': typeof OpenSourceHermesAgentRoute
  '/open-source/jan-ai': typeof OpenSourceJanAiRoute
  '/open-source/kdenlive': typeof OpenSourceKdenliveRoute
  '/open-source/openclaw': typeof OpenSourceOpenclawRoute
  '/open-source/opencut': typeof OpenSourceOpencutRoute
  '/open-source/openhands': typeof OpenSourceOpenhandsRoute
  '/open-source/pocketbase': typeof OpenSourcePocketbaseRoute
  '/open-source/seo-spider': typeof OpenSourceSeoSpiderRoute
  '/open-source/shotcut': typeof OpenSourceShotcutRoute
  '/open-source/tuttle': typeof OpenSourceTuttleRoute
  '/open-source/upscayl': typeof OpenSourceUpscaylRoute
  '/order/$ref': typeof OrderRefRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/open-source/': typeof OpenSourceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/agents'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/desktop-os'
    | '/download'
    | '/faq'
    | '/integrations'
    | '/open-source'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/voice-ai'
    | '/admin/downloads'
    | '/admin/seo'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/features/$slug'
    | '/models/$slug'
    | '/modules/$slug'
    | '/open-source/anythingllm'
    | '/open-source/audacity'
    | '/open-source/deep-live-cam'
    | '/open-source/facefusion'
    | '/open-source/hermes-agent'
    | '/open-source/jan-ai'
    | '/open-source/kdenlive'
    | '/open-source/openclaw'
    | '/open-source/opencut'
    | '/open-source/openhands'
    | '/open-source/pocketbase'
    | '/open-source/seo-spider'
    | '/open-source/shotcut'
    | '/open-source/tuttle'
    | '/open-source/upscayl'
    | '/order/$ref'
    | '/blog/'
    | '/compare/'
    | '/features/'
    | '/models/'
    | '/modules/'
    | '/open-source/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/agents'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/desktop-os'
    | '/download'
    | '/faq'
    | '/integrations'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/voice-ai'
    | '/admin/downloads'
    | '/admin/seo'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/features/$slug'
    | '/models/$slug'
    | '/modules/$slug'
    | '/open-source/anythingllm'
    | '/open-source/audacity'
    | '/open-source/deep-live-cam'
    | '/open-source/facefusion'
    | '/open-source/hermes-agent'
    | '/open-source/jan-ai'
    | '/open-source/kdenlive'
    | '/open-source/openclaw'
    | '/open-source/opencut'
    | '/open-source/openhands'
    | '/open-source/pocketbase'
    | '/open-source/seo-spider'
    | '/open-source/shotcut'
    | '/open-source/tuttle'
    | '/open-source/upscayl'
    | '/order/$ref'
    | '/blog'
    | '/compare'
    | '/features'
    | '/models'
    | '/modules'
    | '/open-source'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/agents'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/desktop-os'
    | '/download'
    | '/faq'
    | '/integrations'
    | '/open-source'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/voice-ai'
    | '/admin/downloads'
    | '/admin/seo'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/features/$slug'
    | '/models/$slug'
    | '/modules/$slug'
    | '/open-source/anythingllm'
    | '/open-source/audacity'
    | '/open-source/deep-live-cam'
    | '/open-source/facefusion'
    | '/open-source/hermes-agent'
    | '/open-source/jan-ai'
    | '/open-source/kdenlive'
    | '/open-source/openclaw'
    | '/open-source/opencut'
    | '/open-source/openhands'
    | '/open-source/pocketbase'
    | '/open-source/seo-spider'
    | '/open-source/shotcut'
    | '/open-source/tuttle'
    | '/open-source/upscayl'
    | '/order/$ref'
    | '/blog/'
    | '/compare/'
    | '/features/'
    | '/models/'
    | '/modules/'
    | '/open-source/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  DesktopOsRoute: typeof DesktopOsRoute
  DownloadRoute: typeof DownloadRoute
  FaqRoute: typeof FaqRoute
  IntegrationsRoute: typeof IntegrationsRoute
  OpenSourceRoute: typeof OpenSourceRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VoiceAiRoute: typeof VoiceAiRoute
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CompareSlugRoute: typeof CompareSlugRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  ModelsSlugRoute: typeof ModelsSlugRoute
  ModulesSlugRoute: typeof ModulesSlugRoute
  OrderRefRoute: typeof OrderRefRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-os': {
      id: '/desktop-os'
      path: '/desktop-os'
      fullPath: '/desktop-os'
      preLoaderRoute: typeof DesktopOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source': {
      id: '/open-source'
      path: '/open-source'
      fullPath: '/open-source'
      preLoaderRoute: typeof OpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-ai': {
      id: '/voice-ai'
      path: '/voice-ai'
      fullPath: '/voice-ai'
      preLoaderRoute: typeof VoiceAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/admin/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$slug': {
      id: '/models/$slug'
      path: '/models/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof ModelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source/': {
      id: '/open-source/'
      path: '/'
      fullPath: '/open-source/'
      preLoaderRoute: typeof OpenSourceIndexRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/anythingllm': {
      id: '/open-source/anythingllm'
      path: '/anythingllm'
      fullPath: '/open-source/anythingllm'
      preLoaderRoute: typeof OpenSourceAnythingllmRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/audacity': {
      id: '/open-source/audacity'
      path: '/audacity'
      fullPath: '/open-source/audacity'
      preLoaderRoute: typeof OpenSourceAudacityRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/deep-live-cam': {
      id: '/open-source/deep-live-cam'
      path: '/deep-live-cam'
      fullPath: '/open-source/deep-live-cam'
      preLoaderRoute: typeof OpenSourceDeepLiveCamRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/facefusion': {
      id: '/open-source/facefusion'
      path: '/facefusion'
      fullPath: '/open-source/facefusion'
      preLoaderRoute: typeof OpenSourceFacefusionRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/hermes-agent': {
      id: '/open-source/hermes-agent'
      path: '/hermes-agent'
      fullPath: '/open-source/hermes-agent'
      preLoaderRoute: typeof OpenSourceHermesAgentRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/jan-ai': {
      id: '/open-source/jan-ai'
      path: '/jan-ai'
      fullPath: '/open-source/jan-ai'
      preLoaderRoute: typeof OpenSourceJanAiRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/kdenlive': {
      id: '/open-source/kdenlive'
      path: '/kdenlive'
      fullPath: '/open-source/kdenlive'
      preLoaderRoute: typeof OpenSourceKdenliveRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/openclaw': {
      id: '/open-source/openclaw'
      path: '/openclaw'
      fullPath: '/open-source/openclaw'
      preLoaderRoute: typeof OpenSourceOpenclawRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/opencut': {
      id: '/open-source/opencut'
      path: '/opencut'
      fullPath: '/open-source/opencut'
      preLoaderRoute: typeof OpenSourceOpencutRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/openhands': {
      id: '/open-source/openhands'
      path: '/openhands'
      fullPath: '/open-source/openhands'
      preLoaderRoute: typeof OpenSourceOpenhandsRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/pocketbase': {
      id: '/open-source/pocketbase'
      path: '/pocketbase'
      fullPath: '/open-source/pocketbase'
      preLoaderRoute: typeof OpenSourcePocketbaseRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/seo-spider': {
      id: '/open-source/seo-spider'
      path: '/seo-spider'
      fullPath: '/open-source/seo-spider'
      preLoaderRoute: typeof OpenSourceSeoSpiderRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/shotcut': {
      id: '/open-source/shotcut'
      path: '/shotcut'
      fullPath: '/open-source/shotcut'
      preLoaderRoute: typeof OpenSourceShotcutRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/tuttle': {
      id: '/open-source/tuttle'
      path: '/tuttle'
      fullPath: '/open-source/tuttle'
      preLoaderRoute: typeof OpenSourceTuttleRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/open-source/upscayl': {
      id: '/open-source/upscayl'
      path: '/upscayl'
      fullPath: '/open-source/upscayl'
      preLoaderRoute: typeof OpenSourceUpscaylRouteImport
      parentRoute: typeof OpenSourceRoute
    }
    '/order/$ref': {
      id: '/order/$ref'
      path: '/order/$ref'
      fullPath: '/order/$ref'
      preLoaderRoute: typeof OrderRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OpenSourceRouteChildren {
  OpenSourceAnythingllmRoute: typeof OpenSourceAnythingllmRoute
  OpenSourceAudacityRoute: typeof OpenSourceAudacityRoute
  OpenSourceDeepLiveCamRoute: typeof OpenSourceDeepLiveCamRoute
  OpenSourceFacefusionRoute: typeof OpenSourceFacefusionRoute
  OpenSourceHermesAgentRoute: typeof OpenSourceHermesAgentRoute
  OpenSourceJanAiRoute: typeof OpenSourceJanAiRoute
  OpenSourceKdenliveRoute: typeof OpenSourceKdenliveRoute
  OpenSourceOpenclawRoute: typeof OpenSourceOpenclawRoute
  OpenSourceOpencutRoute: typeof OpenSourceOpencutRoute
  OpenSourceOpenhandsRoute: typeof OpenSourceOpenhandsRoute
  OpenSourcePocketbaseRoute: typeof OpenSourcePocketbaseRoute
  OpenSourceSeoSpiderRoute: typeof OpenSourceSeoSpiderRoute
  OpenSourceShotcutRoute: typeof OpenSourceShotcutRoute
  OpenSourceTuttleRoute: typeof OpenSourceTuttleRoute
  OpenSourceUpscaylRoute: typeof OpenSourceUpscaylRoute
  OpenSourceIndexRoute: typeof OpenSourceIndexRoute
}

const OpenSourceRouteChildren: OpenSourceRouteChildren = {
  OpenSourceAnythingllmRoute: OpenSourceAnythingllmRoute,
  OpenSourceAudacityRoute: OpenSourceAudacityRoute,
  OpenSourceDeepLiveCamRoute: OpenSourceDeepLiveCamRoute,
  OpenSourceFacefusionRoute: OpenSourceFacefusionRoute,
  OpenSourceHermesAgentRoute: OpenSourceHermesAgentRoute,
  OpenSourceJanAiRoute: OpenSourceJanAiRoute,
  OpenSourceKdenliveRoute: OpenSourceKdenliveRoute,
  OpenSourceOpenclawRoute: OpenSourceOpenclawRoute,
  OpenSourceOpencutRoute: OpenSourceOpencutRoute,
  OpenSourceOpenhandsRoute: OpenSourceOpenhandsRoute,
  OpenSourcePocketbaseRoute: OpenSourcePocketbaseRoute,
  OpenSourceSeoSpiderRoute: OpenSourceSeoSpiderRoute,
  OpenSourceShotcutRoute: OpenSourceShotcutRoute,
  OpenSourceTuttleRoute: OpenSourceTuttleRoute,
  OpenSourceUpscaylRoute: OpenSourceUpscaylRoute,
  OpenSourceIndexRoute: OpenSourceIndexRoute,
}

const OpenSourceRouteWithChildren = OpenSourceRoute._addFileChildren(
  OpenSourceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  DesktopOsRoute: DesktopOsRoute,
  DownloadRoute: DownloadRoute,
  FaqRoute: FaqRoute,
  IntegrationsRoute: IntegrationsRoute,
  OpenSourceRoute: OpenSourceRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VoiceAiRoute: VoiceAiRoute,
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminSeoRoute: AdminSeoRoute,
  BlogSlugRoute: BlogSlugRoute,
  CompareSlugRoute: CompareSlugRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
  ModelsSlugRoute: ModelsSlugRoute,
  ModulesSlugRoute: ModulesSlugRoute,
  OrderRefRoute: OrderRefRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  ModulesIndexRoute: ModulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
