/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DesktopOsRouteImport } from './routes/desktop-os'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VoiceAiRouteImport } from './routes/voice-ai'
import { Route as OrderRefRouteImport } from './routes/order.$ref'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopOsRoute = DesktopOsRouteImport.update({
  id: '/desktop-os',
  path: '/desktop-os',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceAiRoute = VoiceAiRouteImport.update({
  id: '/voice-ai',
  path: '/voice-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRefRoute = OrderRefRouteImport.update({
  id: '/order/$ref',
  path: '/order/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/checkout': typeof CheckoutRoute
  '/desktop-os': typeof DesktopOsRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/voice-ai': typeof VoiceAiRoute
  '/order/$ref': typeof OrderRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/checkout': typeof CheckoutRoute
  '/desktop-os': typeof DesktopOsRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/voice-ai': typeof VoiceAiRoute
  '/order/$ref': typeof OrderRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/checkout': typeof CheckoutRoute
  '/desktop-os': typeof DesktopOsRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/voice-ai': typeof VoiceAiRoute
  '/order/$ref': typeof OrderRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/checkout'
    | '/desktop-os'
    | '/integrations'
    | '/pricing'
    | '/refund'
    | '/terms'
    | '/voice-ai'
    | '/order/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/checkout'
    | '/desktop-os'
    | '/integrations'
    | '/pricing'
    | '/refund'
    | '/terms'
    | '/voice-ai'
    | '/order/$ref'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/checkout'
    | '/desktop-os'
    | '/integrations'
    | '/pricing'
    | '/refund'
    | '/terms'
    | '/voice-ai'
    | '/order/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  CheckoutRoute: typeof CheckoutRoute
  DesktopOsRoute: typeof DesktopOsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PricingRoute: typeof PricingRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  VoiceAiRoute: typeof VoiceAiRoute
  OrderRefRoute: typeof OrderRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-os': {
      id: '/desktop-os'
      path: '/desktop-os'
      fullPath: '/desktop-os'
      preLoaderRoute: typeof DesktopOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-ai': {
      id: '/voice-ai'
      path: '/voice-ai'
      fullPath: '/voice-ai'
      preLoaderRoute: typeof VoiceAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$ref': {
      id: '/order/$ref'
      path: '/order/$ref'
      fullPath: '/order/$ref'
      preLoaderRoute: typeof OrderRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  CheckoutRoute: CheckoutRoute,
  DesktopOsRoute: DesktopOsRoute,
  IntegrationsRoute: IntegrationsRoute,
  PricingRoute: PricingRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  VoiceAiRoute: VoiceAiRoute,
  OrderRefRoute: OrderRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
